// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "L\u1EA5y th\xF4ng tin ng\u01B0\u1EDDi d\xF9ng",
  description: "Get the signed-in user's profile (full name, username, assigned area) and their roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, roles] = await Promise.all([
      supabase.from("profiles").select("full_name, username, email, assigned_area").eq("user_id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (profile.error) return { content: [{ type: "text", text: profile.error.message }], isError: true };
    const result = { profile: profile.data, roles: (roles.data ?? []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-pending-vouchers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_pending_vouchers_default = defineTool2({
  name: "list_pending_vouchers",
  title: "Danh s\xE1ch ch\u1EE9ng t\u1EEB",
  description: "List vouchers visible to the signed-in user, optionally filtered by status (pending, signed, approved) or voucher type.",
  inputSchema: {
    status: z.string().optional().describe("Filter by status, e.g. pending or signed."),
    voucher_type: z.string().optional().describe("Filter by voucher type, e.g. phieu-thu, phieu-chi."),
    limit: z.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, voucher_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("pending_vouchers").select("id, voucher_id, voucher_type, status, created_at, signed_at, printed_at, voucher_data").order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (voucher_type) query = query.eq("voucher_type", voucher_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { vouchers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_notifications_default = defineTool3({
  name: "list_notifications",
  title: "Danh s\xE1ch th\xF4ng b\xE1o",
  description: "List the signed-in user's notifications, newest first. Optionally only unread ones.",
  inputSchema: {
    unread_only: z2.boolean().optional().describe("Return only unread notifications."),
    limit: z2.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("notifications").select("id, title, message, type, is_read, created_at, related_voucher_id, related_voucher_type").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(take);
    if (unread_only) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/mark-notification-read.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var mark_notification_read_default = defineTool4({
  name: "mark_notification_read",
  title: "\u0110\xE1nh d\u1EA5u \u0111\xE3 \u0111\u1ECDc th\xF4ng b\xE1o",
  description: "Mark one of the signed-in user's notifications as read.",
  inputSchema: {
    notification_id: z3.string().describe("The notification id to mark as read.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ notification_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("notifications").update({ is_read: true }).eq("id", notification_id).eq("user_id", ctx.getUserId()).select("id, is_read");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "Notification not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { notification: data[0] }
    };
  }
});

// src/lib/mcp/tools/list-voucher-signatures.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_voucher_signatures_default = defineTool5({
  name: "list_voucher_signatures",
  title: "L\u1ECBch s\u1EED k\xFD duy\u1EC7t",
  description: "List digital signature records for vouchers visible to the signed-in user, newest first.",
  inputSchema: {
    voucher_id: z4.string().optional().describe("Only signatures for this voucher id."),
    limit: z4.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ voucher_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("voucher_signatures").select("*").order("signed_at", { ascending: false }).limit(take);
    if (voucher_id) query = query.eq("voucher_id", voucher_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { signatures: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vyonnsefdfsmnwbgctcb";
var mcp_default = defineMcp({
  name: "quality-life-tools",
  title: "Quality Life Tools",
  version: "0.1.0",
  instructions: "Tools for the Quality Life Tools financial management app (Vietnamese union finance system). Read the signed-in user's profile and roles, list vouchers awaiting signature or already approved, inspect signature history, and read or mark notifications. All data is scoped to the signed-in user by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_pending_vouchers_default, list_notifications_default, mark_notification_read_default, list_voucher_signatures_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
